"use client";

import { FormEvent, useEffect, useState } from "react";
import type { Thesis } from "@/lib/schemas";
import { TagInput } from "../components/TagInput";
import { ErrorState, LoadingState, PageHeader, buttonClass, cardClass, inputClass } from "../components/ui";

export default function ThesisPage() {
  const [thesis, setThesis] = useState<Thesis | null>(null);
  const [error, setError] = useState("");
  const [saving, setSaving] = useState(false);
  const [saved, setSaved] = useState(false);
  async function load() { try { const response = await fetch("/api/thesis", { cache: "no-store" }); if (!response.ok) throw new Error("Could not load the investment thesis"); setThesis(await response.json() as Thesis); setError(""); } catch (err) { setError(err instanceof Error ? err.message : "Could not load thesis"); } }
  useEffect(() => { void load(); }, []);
  async function save(event: FormEvent) { event.preventDefault(); if (!thesis) return; setSaving(true); setSaved(false); setError(""); try { const response = await fetch("/api/thesis", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(thesis) }); if (!response.ok) { const payload = await response.json().catch(() => null) as { error?: string } | null; throw new Error(payload?.error || "Could not save thesis"); } setThesis(await response.json() as Thesis); setSaved(true); window.setTimeout(() => setSaved(false), 2500); } catch (err) { setError(err instanceof Error ? err.message : "Could not save thesis"); } finally { setSaving(false); } }
  return <><PageHeader eyebrow="Investment criteria" title="Thesis" description="These constraints guide sourcing, screening, and investment decisions." />{error && <div className="mb-5"><ErrorState message={error} retry={() => void load()} /></div>}{!thesis ? <LoadingState label="Loading thesis" /> : <form onSubmit={save} className="space-y-5"><section className={`${cardClass} p-5 sm:p-6`}><h2 className="font-semibold text-slate-100">Mandate</h2><p className="mt-1 text-xs text-slate-500">Press Enter or comma to add list values.</p><div className="mt-5 grid gap-5 lg:grid-cols-3"><Field label="Sectors"><TagInput value={thesis.sectors} onChange={(sectors) => setThesis({ ...thesis, sectors })} placeholder="Add a sector" /></Field><Field label="Geographies"><TagInput value={thesis.geographies} onChange={(geographies) => setThesis({ ...thesis, geographies })} placeholder="Add a geography" /></Field><Field label="Stages"><TagInput value={thesis.stages} onChange={(stages) => setThesis({ ...thesis, stages })} placeholder="Add a stage" /></Field></div></section><section className={`${cardClass} p-5 sm:p-6`}><h2 className="font-semibold text-slate-100">Economics & risk</h2><div className="mt-5 grid gap-5 sm:grid-cols-3"><Field label="Check size (USD)"><input required min={0} step={1000} type="number" className={`${inputClass} font-mono`} value={thesis.checkSizeUsd} onChange={(event) => setThesis({ ...thesis, checkSizeUsd: Number(event.target.value) })} /></Field><Field label="Ownership target (%)"><input required min={0} max={100} step={.1} type="number" className={`${inputClass} font-mono`} value={thesis.ownershipTargetPct} onChange={(event) => setThesis({ ...thesis, ownershipTargetPct: Number(event.target.value) })} /></Field><Field label="Risk appetite"><select className={inputClass} value={thesis.riskAppetite} onChange={(event) => setThesis({ ...thesis, riskAppetite: event.target.value as Thesis["riskAppetite"] })}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></Field></div></section><section className={`${cardClass} p-5 sm:p-6`}><h2 className="font-semibold text-slate-100">High-signal investors</h2><p className="mt-1 text-xs text-slate-500">Used as a revealed-quality signal in funding and competitor analysis.</p><div className="mt-5"><TagInput value={thesis.highSignalInvestors} onChange={(highSignalInvestors) => setThesis({ ...thesis, highSignalInvestors })} placeholder="Add investor" /></div></section><div className="flex items-center justify-end gap-3"><span className={`text-xs text-emerald-300 transition ${saved ? "opacity-100" : "opacity-0"}`}>Saved</span><button disabled={saving} className={buttonClass}>{saving ? "Saving…" : "Save thesis"}</button></div></form>}</>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="mb-2 block text-xs font-medium text-slate-400">{label}</span>{children}</label>; }
